apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-webhook-jenkins-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-webhook-jenkins-app
  template:
    metadata:
      labels:
        app: spring-boot-webhook-jenkins-app
    spec:
      containers:
        - name: spring-boot-app
          image: host.docker.internal:8082/spring-boot-webhook-jenkins:1.0.0
          ports:
            - containerPort: 8085